application: smstweet
version: 1
runtime: python
api_version: 1

handlers:
    
- url: /stylesheets
  static_dir: stylesheets
    
- url: /images
  static_dir: images
  
- url: /test
  script: main.py
  login: admin

- url: .*
  script: main.py

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

